model_id: NousResearch/Llama-2-7b-chat-hf
model_family: llama2-7b
gaudi_config_name: Habana/llama

LoRA:
  r: 8
  alpha: 32
  dropout: 0.05

data_path: ../DrvKnowledge/a_new_data/retain75.csv
split: full
batch_size: 4
gradient_accumulation_steps: 1
num_epochs: 10
save_dir: /save_dir
lr: 1e-4
weight_decay: 0
seed: 42
